### ISSUE TITLE
TypeError: Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by NemoN** [iobroker-community-adapters/ioBroker.info#46]
Ubuntu minimal 18.04 installation
ioBroker heute via Script installiert

Wenn ich /opt/iobroker/node_modules/iobroker.info/node_modules/systeminformation/lib/util.js Zeile 40 auskommentiere läuft es 

```
host.iobrokerdev | 2019-06-19 14:53:20.714 | error | instance system.adapter.info.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Module._compile (module.js:653:30)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.info/node_modules/systeminformation/lib/index.js:25:14)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at require (internal/module.js:11:18)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Module.require (module.js:597:17)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Function.Module._load (module.js:498:3)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at tryModuleLoad (module.js:506:12)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Module.load (module.js:566:32)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Module._compile (module.js:653:30)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.info/node_modules/systeminformation/lib/util.js:40:32)
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: TypeError: Cannot read property 'env' of undefined
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: ^
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: env: util._extend({}.process.env, { LANG: 'en_US.UTF-8' })
Caught | 2019-06-19 14:53:20.714 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.info/node_modules/systeminformation/lib/util.js:40
```

**Comment by jorinkl** [comment]
Same here

**Comment by ldittmar81** [comment]
https://github.com/sebhildebrandt/systeminformation/issues/245

Should be fixed now!
