### ISSUE TITLE
info-adapter seems not to be compatible with node 16.x

### ISSUE THREAD

**Issue by brkai** [iobroker-community-adapters/ioBroker.info#465]
can anyone confirm?

- updated to node 16, as info itself recommended.
- info-adapter won't run any longer

what i tried quick and dirty:
removal of folder /opt/iobroker/node_modules/systeminformation/
re-install of adapter "info" 
--> no change of behavior :-(

LOG:
------------------------------------------------------------------------------------------------
info.0
	2022-07-10 08:48:20.528	error	line is not defined
info.0
	2022-07-10 08:48:20.528	error	ReferenceError: line is not defined at filterLines (/opt/iobroker/node_modules/systeminformation/lib/filesystem.js:66:9) at /opt/iobroker/node_modules/systeminformation/lib/filesystem.js:127:23 at ChildProcess.exithandler (node:child_process:390:7) at ChildProcess.emit (node:events:527:28) at maybeClose (node:internal/child_process:1092:16) at Socket.<anonymous> (node:internal/child_process:451:11) at Socket.emit (node:events:527:28) at Pipe.<anonymous> (node:net:709:12)
info.0
	2022-07-10 08:48:20.526	error	uncaught exception: line is not defined

**Comment by ckuratle** [comment]
same problem here

**Comment by aski71** [comment]
same problem here after upgrading node from 16.15.1 to 16.16.0

`

2022-07-10 20:40:27.013 | error | line is not defined
-- | -- | --
info.0 | 2022-07-10 20:40:27.012 | error | ReferenceError: line is not defined at filterLines (/opt/iobroker/node_modules/systeminformation/lib/filesystem.js:66:9) at /opt/iobroker/node_modules/systeminformation/lib/filesystem.js:127:23 at ChildProcess.exithandler (node:child_process:390:7) at ChildProcess.emit (node:events:527:28) at maybeClose (node:internal/child_process:1092:16) at Socket.<anonymous> (node:internal/child_process:451:11) at Socket.emit (node:events:527:28) at Pipe.<anonymous> (node:net:709:12)
info.0 | 2022-07-10 20:40:27.008 | error | uncaught exception: line is not defined

`

**Comment by aski71** [comment]
2022-07-10 20:40:27.013 | error | line is not defined
-- | -- | --
info.0 | 2022-07-10 20:40:27.012 | error | ReferenceError: line is not defined at filterLines (/opt/iobroker/node_modules/systeminformation/lib/filesystem.js:66:9) at /opt/iobroker/node_modules/systeminformation/lib/filesystem.js:127:23 at ChildProcess.exithandler (node:child_process:390:7) at ChildProcess.emit (node:events:527:28) at maybeClose (node:internal/child_process:1092:16) at Socket.<anonymous> (node:internal/child_process:451:11) at Socket.emit (node:events:527:28) at Pipe.<anonymous> (node:net:709:12)
info.0 | 2022-07-10 20:40:27.008 | error | uncaught exception: line is not defined

**Comment by Grothesk242** [comment]
No problem here on a Raspberry Pi 4 (8GB). 
What hardware are you running? 

```
2022-07-11 19:28:17.409  - info: host.chet instance system.adapter.info.0 started with pid 122323
2022-07-11 19:28:21.663  - info: info.0 (122323) starting. Version 1.9.19 in /opt/iobroker/node_modules/iobroker.info, node: v18.5.0, js-controller: 4.0.23
2022-07-11 19:28:21.849  - info: info.0 (122323) Reading/updating systemdata.
2022-07-11 19:28:22.838  - info: info.0 (122323) cpu Temp res = {"main":41.868,"cores":[],"max":41.868,"socket":[],"chipset":null}
2022-07-11 19:28:26.213  - info: info.0 (122323) Reading network data every 120 seconds.
```

**Comment by RelaxedHome** [comment]
I have the same problem.

RPI 4 4 GB 
OS Bullseye
Node 16.16.0
NPM 8.11.0
JS Controller 4.0.23
Admin 5.3.8

**Comment by brkai** [comment]
Great hint, matthias!
Thanks for the Information.

So, the easy way for me to resolve the issue was:
Go to /opt/iobroker/node_modules/
delete folder "systeminformation".
(Maybe it also works without deletion of the folder...)
Install same Version of ioBroker.info again over the installed one.

/opt/iobroker/node_modules/systeminformation
will now contain v. 5.12.0 which was released ~3hrs ago
and everything runs smoothly as before ;-)

**Comment by klein0r** [comment]
> So, the easy way for me to resolve the issue was:
> Go to /opt/iobroker/node_modules/
> delete folder "systeminformation".
> (Maybe it also works without deletion of the folder...)
> Install same Version of ioBroker.info again over the installed one.

**Please don't modify dependencies on your own. That was a hint for the devs to increate the dependency in the package.json.**

**Comment by bahnuhr** [comment]
Beide Lösungen funktionieren bei mir nicht.
a) install 1.9.9
b) löschen Ordner "systeminformation"

Habe beides versucht. Fehler bleibt.
Gibts noch ne andere Idee / Lösung ?

**Comment by bahnuhr** [comment]
Hatte alles probiert,
dann letzter versuch alles deinstalliert (auch den Adapter).
Und dann wieder neu installiert.
Jetzt läuft es (komisch, dachte das hatte ich schon einmal gemacht).
Fazit:
läuft jetzt
(bei mir war es eine komplett neue Installation)
