### ISSUE TITLE
Adapter Red, Errors in Protocol

### ISSUE THREAD

**Issue by DPO99** [iobroker-community-adapters/ioBroker.info#689]
**Describe the bug**  
Adapter does not work. Red Light and Error Messages in Protocoll

**To Reproduce**  
1. Acitvate Adapter/Run

**Expected behavior**  
Adpater works without any issues

**Screenshots & Logfiles**  
```

host.raspberrypi | 2024-01-13 22:54:29.136 | info | Restart adapter system.adapter.info.0 because enabled -- | -- | -- | --
host.raspberrypi | 2024-01-13 22:54:29.136 | error | instance system.adapter.info.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: Node.js v18.19.0
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at node:internal/main/run_main_module:28:49
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Module._load (node:internal/modules/cjs/loader:1013:12)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Module.load (node:internal/modules/cjs/loader:1197:32)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Module._compile (node:internal/modules/cjs/loader:1356:14)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.info/main.js:58:18)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: at getSystemVersions (/opt/iobroker/node_modules/iobroker.info/main.js:89:11)
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'log')
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: ^
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: adapter.log.error("Could not check npm version: " + e);
host.raspberrypi | 2024-01-13 22:54:29.136 | error | Caught by controller[1]: /opt/iobroker/node_modules/iobroker.info/main.js:89
host.raspberrypi | 2024-01-13 22:54:29.135 | error | Caught by controller[0]: /bin/sh: 1: npm: not found
host.raspberrypi | 2024-01-13 22:54:28.494 | info | instance system.adapter.info.0 started with pid 1554
host.raspberrypi | 2024-01-13 22:54:28.469 | info | "system.adapter.info.0" enabled
host.raspberrypi | 2024-01-13 22:53:58.721 | info | instance system.adapter.systeminfo.0 terminated with code 11 
```

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: Bookworm on RaspberryPI 5

**Comment by DPO99** [comment]
https://forum.iobroker.net/topic/71461/dfsg-nodejs-eingehandelt-hier-die-korrektur
